#pragma once

#include "pch.h"
#include "Puzzle.h"
#include "Core.h"

DECLARE_PUZZLE(01)
DECLARE_PUZZLE(02)
DECLARE_PUZZLE(03)
DECLARE_PUZZLE(04)
DECLARE_PUZZLE(05)
DECLARE_PUZZLE(06)
DECLARE_PUZZLE(07)
DECLARE_PUZZLE(08)
DECLARE_PUZZLE(09)
DECLARE_PUZZLE(10)
DECLARE_PUZZLE(11)
DECLARE_PUZZLE(12)
DECLARE_PUZZLE(13)
DECLARE_PUZZLE(14)
DECLARE_PUZZLE(15)
DECLARE_PUZZLE(16)
DECLARE_PUZZLE(17)
DECLARE_PUZZLE(18)
DECLARE_PUZZLE(19)
DECLARE_PUZZLE(20)
DECLARE_PUZZLE(21)
DECLARE_PUZZLE(22)
DECLARE_PUZZLE(23)
DECLARE_PUZZLE(24)
DECLARE_PUZZLE(25)
